{% set name = "kmc_smudge_pairs" %}
{% set version = "3.1.2rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gkanogiannis/KMC/archive/v{{ version }}.tar.gz
  sha256: 901a7f3dada3507cbce679611d9fa5361fe4c26ffa85f3bbf0739f071743488f

build:
  skip: true  # [win]
  script: bash build_static.sh
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - zlib
    - bzip2
  run:
    - zlib
    - bzip2

test:
  commands:
    - kmc --help

about:
  home: https://github.com/gkanogiannis/KMC
  summary: 'Fast and frugal disk based k-mer counter. Includes smudge_pairs.'
  license: GPL-3.0-or-later
  license_file: 
    - LICENSE.txt
    - vendor-licenses/

extra:
  recipe-maintainers:
    - gkanogiannis
