{% set name = "kmc_smudge_pairs" %}
{% set version = "3.1.2rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gkanogiannis/KMC/archive/v{{ version }}.tar.gz
  sha256: 0f66b0c42291c58cf52dd5b20e98803cad14deb2a3f7c0dfc1042ab3c1a19be7

build:
  skip: true  # [win]
  script: bash build_static.sh
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - kmc_smudge_pairs

about:
  home: https://github.com/gkanogiannis/KMC
  summary: 'Fast and frugal disk based k-mer counter. Includes smudge_pairs.'
  license: GPL-3.0-or-later
  license_file: 
    - LICENSE.txt
    - vendor-licenses/

extra:
  recipe-maintainers:
    - gkanogiannis
