{% set name = "kmc_smudge_pairs" %}
{% set version = "v3.1.2rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/gkanogiannis/KMC.git
  git_tag: {{ version }}
  sha256: 495a8d51267b2e4f0694d270e49edd1e676df5fcae56c151060446dcb4933b2e

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/gkanogiannis/KMC
  summary: 'Fast and frugal disk based k-mer counter. Includes smudge_pairs.'
  license: GPL-3.0-or-later
  license_file: 
    - LICENSE.txt
    - vendor-licenses/

extra:
  recipe-maintainers:
    - gkanogiannis
