{% set name = "kmc_smudge_pairs" %}
{% set version = "3.1.2rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gkanogiannis/KMC/archive/v{{ version }}.tar.gz
  sha256: 4454cbb4db93337dfa7d0fd18e69036962709f8dc2e1e812c3e8cec4c6978b73

build:
  skip: true  # [win]
  script: build_static.sh
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/gkanogiannis/KMC
  summary: 'Fast and frugal disk based k-mer counter. Includes smudge_pairs.'
  license: GPL-3.0-or-later
  license_file: 
    - LICENSE.txt
    - vendor-licenses/

extra:
  recipe-maintainers:
    - gkanogiannis
